# yaml-language-server: $schema=service: peerpilot-document-processor
service: peerpilot-document-processor

provider:
  name: aws
  runtime: python3.12
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  
  environment:
    S3_BUCKET_NAME: peerpilot-kiro-data
    AWS_DEFAULT_REGION: us-east-1
  
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:GetObjectVersion
      Resource:
        - "arn:aws:s3:::peerpilot-kiro-data/*"
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
        - s3:DeleteObject
      Resource:
        - "arn:aws:s3:::peerpilot-kiro-data/*"
    - Effect: Allow
      Action:
        - s3:ListBucket
        - s3:GetBucketLocation
        - s3:CreateBucket
      Resource:
        - "arn:aws:s3:::peerpilot-kiro-data"
    - Effect: Allow
      Action:
        - textract:StartDocumentTextDetection
        - textract:GetDocumentTextDetection
        - textract:AnalyzeDocument
      Resource: "*"
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"

functions:
  processDocument:
    handler: lambda_function.lambda_handler
    timeout: 300
    memorySize: 512
    events:
      - s3:
          bucket: peerpilot-kiro-data
          existing: true
          event: s3:ObjectCreated:*
          rules:
            - prefix: input-articles/

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: peerpilot-kiro-data
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
